### PR TITLE
Fixed gem installation to include new required JAR's added in a previous commit.  Fixed installation documenation.

### PR DESCRIPTION
**Pull request by benjcooley**
- Previous commit added dependencies to new JAR files which now cause plugin to fail to load on new install.  Added all of these JAR files to the gemspec.
- Added corrected documentation for installation, mainly using jruby -S to avoid interaction with regular ruby, and to directly install plugin gem before installing plugin.

### CODE REVIEW

**Comment by milodky** [comment]
Hi @benjcooley , I followed the new instructions you provided, but still I got such error:

~/Documents/Work/logstash$ /opt/logstash/bin/logstash -f es_dynamo_test.conf 
The error reported is: 

```
you might need to reinstall the gem which depends on the missing jar or in case there is Jars.lock then JARS_RESOLVE=true will install the missing jars
```

no such file to load -- com/amazonaws/aws-java-sdk-elasticbeanstalk/1.10.11/aws-java-sdk-elasticbeanstalk-1.10.11 (LoadError)

**Comment by marcosnils** [comment]
@milodky have you tried following the instructions I've provided?

**Comment by milodky** [comment]
@marcosnils yes but it didn't work either with the old master branch. I'll try with this new branch.

**Comment by milodky** [comment]
Hi @marcosnils ,  this branch combined with the dockerfile solved the problem! Thanks!

**Comment by marcosnils** [comment]
@milodky interesting. I didn't have to use this branch for my setup to work. I'm glad that the dockerfile helped!.

**Comment by rauljim** [comment]
I couldn't get the plugin to work following awslab's instructions. I just followed the instructions in this PS and now everything works great.
Thanks!

**Comment by tshrikant** [comment]
It worked super cool! However, I do not see real time data in output. I have to restart service to see the data. Anyone got any ideas that I should try?

**Pull request merged**
